name: Postman tests

on:
  push:
    branches:
      - refs/heads/tools-qa-postman-ui-tests 
  pull_request:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install newman
        run: npm install -g newman

      - name: Run Postman collection
        run: newman run ./postman_collection/GroceryStoreAPI.postman_collection.json

  ui-tests:
    needs: postman-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci # or pip install -r requirements.txt, etc.

      - name: Run UI tests
        run: npm run test:ui # or your actual UI test command